### ISSUE TITLE
Roadmap for the project.

### ISSUE THREAD

**Issue by Souvikns** [Souvikns/glee-browser#3]
> In this issue, we will try to plan ahead the roadmap for the project and define its goals for our development. 

The main goal for the project is to support all the features currently supported by Glee and make it stable enough to showcase to the community and then donate it to the AsyncAPI. 

For development we need to focus on two things - 

We need to add more adapters, as we currently support WebSocket adapters. I think showcasing support for only `MQTT` and `WebSocket` would do. We should not try to do HTTP as the current spec does not fully support it and we should try it after version 3 rolls out. 
- [ ] add MQTT protocol support  
- [ ] add socket.io support 
- [ ] add Kafka support ( Less important right now)

Make the internal library stable, currently the project is basically a copy of glee, but since this is lirbary significantly different from glee, we might need to reconsider the way we build it. 

- [ ] Add config support
- [ ] Support for Authentication 
- [ ] support for once function. 
- [ ] Support for retries
